package org.odata4j.test;


//@RunWith(Suite.class)
//@Suite.SuiteClasses({
//    ExpressionTest.class,
//    JsonTest.class,
//    PojoTest.class,
//    ScenarioTest.class,
//    TypeConverterTest.class,
//    Issue10.class,
//    Issue13.class,
//    Issue15.class,
//    Issue16.class,
//    ResourcePathTest.class,
//    QueryOptionTest.class,
//    QueryOptionTest50.class,
//    QueryOptionAtomTest.class,
//    QueryOptionAtomTest50.class,
//    DateTimeFormatTest.class,
//    CreateTest.class,
//    UpdateTest.class,
//    DeleteTest.class,
//    EdmTimeTemporalTest.class,
//    EdmDateTimeTemporalTest.class,
//    CreateWithLinkTest.class,
//    CreateWithLink2Test.class,
//    OEntityKeyTest.class,
//    CompositeKeyEntityTest.class,
//    Oneoff01_Unidirectional.class,
//    Oneoff02_ManyToManyWithoutMappedName.class,
//    Oneoff03_ManyToMany.class,
//    AtomFeedFormatParserTest.class,
//    LinksTest.class,
//    EdmxFormatParserTest.class,
//    EdmxFormatWriterTest.class,
//    FunctionTest.class,
//    EdmSimpleTypeTest.class,
//    EdmTypeTest.class,
//    MultipleWorkspacesTest.class,
//    ClientFactoryTest.class,
//    OFunctionParametersTest.class,
//    OCollectionsTest.class,
//    OPropertiesTest.class,
//    OSimpleObjectsTest.class,
//    InMemoryProducerTest.class,
//    ConsumerLinksTest.class,
//    ConsumerExpandTest.class,
//    HeaderMapTest.class,
//    InMemoryEvaluationTest.class
//})
public class OData4jTestSuite {
}
